name: CICD workflow

on:
  push:
    branches:
        - main

env:
  AZURE_WEB_APP: "Cookify"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .net Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      
      - name: Restore dependencies
        run: dotnet restore ./Cookify/Cookify.csproj

      - name: Build project
        run: dotnet build ./Cookify/Cookify.csproj --configuration Release

      - name: Publish project
        run: dotnet publish ./Cookify/Cookify.csproj --configuration Release --output ./publish

      - name: Deploy to webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEB_APP }}
          publish-profile: ${{ secrets.AZURE_KEY }}
          package: ./publish